default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: recipe_app_rails_group_project_development
  username: postgres
  password: 654321 
test:
  <<: *default
  database: recipe_app_rails_group_project_test
  username: postgres
  password: 654321 

production:
  <<: *default
  database: recipe_app_rails_group_project_production
  username: my_rails_blog
  password: <%= ENV["MY_RAILS_BLOG_DATABASE_PASSWORD"] %>