default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: recipe_app_rails_group_project_development
  username: gich
  password: root

test:
  <<: *default
  database: recipe_app_rails_group_project_test
  username: gich
  password: root

production:
  <<: *default
  database: foods_and_recipes
  username: foods_and_recipes_user
  password: giApCJKqeYI6zgAyxrMeeuA99RaE3clw
  host: dpg-cm2aa821hbls73eov3t0-a
  port: 5432
